# Generated by Django 6.0 on 2025-12-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
